import React,{useMemo,useState} from 'react';
import {Alert,Pressable,SafeAreaView,ScrollView,StatusBar,StyleSheet,Text,TextInput,View} from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import {LinearGradient} from 'expo-linear-gradient';

type Quality='2160p'|'1440p'|'1080p+'|'1080p'|'720p'|'480p';
type Row={name:string;uri:string;size:number;title:string;source:Quality;type:'movie'|'episode'};
const qualities:Quality[]=['2160p','1440p','1080p+','1080p','720p','480p'];
const infer=(name:string):Quality=>/2160|4k/i.test(name)?'2160p':/1440/i.test(name)?'1440p':/1080.*plus|fhd\+/i.test(name)?'1080p+':/1080/i.test(name)?'1080p':/720/i.test(name)?'720p':'480p';

export default function App(){
  const [rows,setRows]=useState<Row[]>([]);
  const [endpoint,setEndpoint]=useState('http://192.168.1.2:8765');
  const [busy,setBusy]=useState(false);
  const estimate=useMemo(()=>rows.length*12,[rows]);
  const pick=async()=>{const result=await DocumentPicker.getDocumentAsync({type:'video/*',multiple:true,copyToCacheDirectory:false});if(result.canceled)return;setRows(v=>[...v,...result.assets.map(a=>{const q=infer(a.name);return{name:a.name,uri:a.uri,size:a.size||0,title:a.name.replace(/\.[^.]+$/,''),source:q,type:'movie' as const}})])};
  const setQuality=(index:number,q:Quality)=>setRows(v=>v.map((r,i)=>i===index?{...r,source:q}:r));
  const upload=async()=>{if(!rows.length)return;setBusy(true);try{const form=new FormData();form.append('plan',JSON.stringify({items:rows.map(r=>({source:r.name,title:r.title,content_type:r.type,source_quality:r.source,target_qualities:[r.source],video_codec:'copy',audio_codec:'copy',group_key:`${r.title}|${r.type}`}))}));rows.forEach(r=>form.append('files',{uri:r.uri,name:r.name,type:'video/x-matroska'} as any));const response=await fetch(`${endpoint.replace(/\/$/,'')}/v1/batches`,{method:'POST',body:form});const data=await response.json();if(!response.ok)throw new Error(data.detail||'Yükleme başlatılamadı');Alert.alert('Batch sıraya alındı',`İş kimliği: ${data.id}\nVideo kalite kaybı olmadan işlenecek.`)}catch(e){Alert.alert('Hata',e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
  return <SafeAreaView style={s.root}><StatusBar barStyle="light-content"/><LinearGradient colors={['#1b0b11','#08080c']} style={s.header}><Text style={s.brand}>O  ODIUMFLIX</Text><Text style={s.studio}>STUDIO α2</Text><Text style={s.h1}>Kayıpsız Mobil Batch</Text><Text style={s.lead}>Dosyalar Windows worker'a gönderilir. Seçtiğin kalite yalnız etikettir; video küçültülmez veya yeniden kodlanmaz.</Text></LinearGradient><ScrollView contentContainerStyle={s.body}><Text style={s.label}>Windows worker adresi</Text><TextInput style={s.input} value={endpoint} onChangeText={setEndpoint} autoCapitalize="none"/><Pressable style={s.pick} onPress={pick}><Text style={s.pickIcon}>＋</Text><Text style={s.pickTitle}>Dosyaları seç</Text><Text style={s.muted}>MKV, MP4 veya hazır kalite sürümleri</Text></Pressable>{rows.map((row,index)=><View style={s.card} key={`${row.uri}-${index}`}><View style={s.cardHead}><View><Text style={s.title}>{row.title}</Text><Text style={s.muted}>{row.name} · {(row.size/1024/1024/1024).toFixed(2)} GB</Text></View><Pressable onPress={()=>setRows(v=>v.filter((_,i)=>i!==index))}><Text style={s.remove}>Sil</Text></Pressable></View><Text style={s.smallLabel}>Kalite etiketi — görüntüyü değiştirmez</Text><View style={s.pills}>{qualities.map(q=><Pressable key={q} style={[s.pill,row.source===q&&s.pillOn]} onPress={()=>setQuality(index,q)}><Text style={[s.pillText,row.source===q&&s.pillTextOn]}>{q}</Text></Pressable>)}</View><Text style={s.lossless}>Video politikası: stream copy · 0 yeniden kodlama</Text></View>)}<View style={s.summary}><View><Text style={s.number}>{rows.length}</Text><Text style={s.muted}>kalite dosyası</Text></View><View><Text style={s.number}>{estimate}</Text><Text style={s.muted}>tahmini çıktı</Text></View><View><Text style={s.number}>0×</Text><Text style={s.muted}>video encode</Text></View></View><Pressable disabled={busy||!rows.length} style={[s.upload,(busy||!rows.length)&&s.disabled]} onPress={upload}><Text style={s.uploadText}>{busy?'Gönderiliyor…':'Kayıpsız batch başlat'}</Text></Pressable><Text style={s.note}>Aynı başlık altındaki farklı kalite dosyaları tek asset olur ve tek ortak ses setini kullanır.</Text></ScrollView></SafeAreaView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#08080c'},header:{padding:22,paddingTop:28,borderBottomWidth:1,borderBottomColor:'#ffffff12'},brand:{color:'#fff',fontWeight:'900',letterSpacing:1.5},studio:{color:'#ff5f7f',fontSize:10,letterSpacing:4,marginLeft:25},h1:{color:'#fff',fontSize:28,fontWeight:'800',marginTop:22},lead:{color:'#a0a0ad',lineHeight:20,marginTop:8},body:{padding:16,paddingBottom:50},label:{color:'#aaa',fontSize:12,marginBottom:7},input:{height:46,borderRadius:12,borderWidth:1,borderColor:'#ffffff18',backgroundColor:'#111116',color:'#fff',paddingHorizontal:12,marginBottom:14},pick:{height:155,borderRadius:17,borderWidth:1,borderStyle:'dashed',borderColor:'#ff537633',backgroundColor:'#ff365f0b',alignItems:'center',justifyContent:'center'},pickIcon:{color:'#ff5c7d',fontSize:35},pickTitle:{color:'#fff',fontWeight:'700'},muted:{color:'#777784',fontSize:11,marginTop:3},card:{backgroundColor:'#111116',borderWidth:1,borderColor:'#ffffff10',borderRadius:15,padding:14,marginTop:10},cardHead:{flexDirection:'row',justifyContent:'space-between'},title:{color:'#fff',fontWeight:'700',maxWidth:260},remove:{color:'#ff6684'},smallLabel:{color:'#a5a5b0',fontSize:11,marginTop:13},pills:{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:8},pill:{borderWidth:1,borderColor:'#ffffff15',paddingHorizontal:9,paddingVertical:6,borderRadius:8},pillOn:{borderColor:'#ff5475',backgroundColor:'#ff365f20'},pillText:{color:'#777784',fontSize:11},pillTextOn:{color:'#fff'},lossless:{color:'#4fd6a3',fontSize:11,marginTop:10},summary:{flexDirection:'row',justifyContent:'space-around',backgroundColor:'#111116',borderRadius:15,padding:15,marginTop:14},number:{color:'#fff',fontSize:23,fontWeight:'800',textAlign:'center'},upload:{backgroundColor:'#ff365f',height:50,borderRadius:13,alignItems:'center',justifyContent:'center',marginTop:14},disabled:{opacity:.4},uploadText:{color:'#fff',fontWeight:'800'},note:{color:'#686875',fontSize:11,textAlign:'center',lineHeight:17,marginTop:12}});
