import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, BarChart3, Bell, ChevronDown, CloudUpload, Film, Gauge, Image, LayoutDashboard, Library, MoreHorizontal, Play, Plus, Search, Settings, Subtitles, Users, WandSparkles} from 'lucide-react';
import {catalog} from '@odiumflix/catalog';
import './styles.css';

const nav=[['Genel Bakış',LayoutDashboard],['İçerikler',Library],['Yeni Yayın',Plus],['Medya İşleme',WandSparkles],['Görseller',Image],['Altyazı & Ses',Subtitles],['Analiz',BarChart3],['Kullanıcılar',Users]] as const;
const App=()=>{const [active,setActive]=useState('Genel Bakış');const [upload,setUpload]=useState(false);return <div className="studio-shell">
<aside><div className="logo"><span>O</span><div>ODIUMFLIX<small>STUDIO</small></div></div><nav>{nav.map(([label,Icon])=><button key={label} className={active===label?'active':''} onClick={()=>setActive(label)}><Icon size={19}/>{label}{label==='Medya İşleme'&&<i>2</i>}</button>)}</nav><div className="aside-bottom"><button><Settings/>Ayarlar</button><div className="profile"><span>KA</span><div><strong>Kerem Aslı</strong><small>Yönetici</small></div><ChevronDown size={16}/></div></div></aside>
<main><header><div><p>OdiumFlix Studio</p><h1>{active}</h1></div><div className="head-actions"><label><Search size={18}/><input placeholder="İçeriklerde ara"/></label><button className="bell"><Bell size={19}/><i/></button><button className="publish" onClick={()=>setUpload(true)}><CloudUpload size={18}/>Yeni içerik yükle</button></div></header>
<section className="welcome"><div><p>PERŞEMBE, 16 TEMMUZ</p><h2>Günaydın, Kerem.</h2><span>Arşivinde bugün her şey yolunda görünüyor.</span></div><div className="health"><Gauge/><div><strong>%98</strong><span>Sistem sağlığı</span></div></div></section>
<section className="stats"><Stat icon={<Film/>} value="24" label="Toplam içerik" note="+3 bu ay"/><Stat icon={<Play/>} value="1.284" label="Toplam izlenme" note="%18 artış"/><Stat icon={<Activity/>} value="87,4%" label="Tamamlama oranı" note="Son 30 gün"/><Stat icon={<Users/>} value="132" label="Aktif izleyici" note="Son 7 gün"/></section>
<div className="dashboard-grid"><section className="panel library"><div className="panel-head"><div><h3>İçerik Kitaplığı</h3><p>Son eklenen ve güncellenen yapımlar</p></div><button>Tümünü gör</button></div><table><thead><tr><th>İçerik</th><th>Durum</th><th>Kalite</th><th>Ses / Altyazı</th><th>İzlenme</th><th/></tr></thead><tbody>{catalog.slice(0,5).map((item,i)=><tr key={item.id}><td><img src={item.poster}/><div><strong>{item.title}</strong><small>{item.year} · {item.duration}</small></div></td><td><span className={i===2?'scheduled':'live'}>{i===2?'Planlandı':'Yayında'}</span></td><td><b className="quality">{item.qualities[0]}</b></td><td>{item.audio.length} ses · {item.subtitles.length} altyazı</td><td>{[427,318,211,196,132][i]}</td><td><MoreHorizontal/></td></tr>)}</tbody></table></section>
<section className="panel pipeline"><div className="panel-head"><div><h3>Medya İşleme</h3><p>Aktif dönüştürme görevleri</p></div><button><MoreHorizontal/></button></div><Job title="Gece Vardiyası.mkv" stage="HLS paketleniyor" progress={72} eta="12 dk kaldı"/><Job title="Sessiz Sokak.mkv" stage="Altyazılar ayrıştırılıyor" progress={38} eta="26 dk kaldı"/><div className="storage"><div><CloudUpload/><span>Hugging Face depolama</span><strong>2,4 TB / 10 TB</strong></div><i><b/></i><small>Kaynak dosyalar, yayın paketleri ve görseller</small></div></section></div>
<section className="lower-grid"><div className="panel chart"><div className="panel-head"><div><h3>İzlenme Aktivitesi</h3><p>Son 7 gün</p></div><select><option>Bu hafta</option></select></div><div className="bars">{[34,52,45,73,61,88,76].map((h,i)=><div key={i}><i style={{height:`${h}%`}}/><span>{['Pzt','Sal','Çar','Per','Cum','Cmt','Paz'][i]}</span></div>)}</div></div><div className="panel quick"><h3>Hızlı işlemler</h3><button onClick={()=>setUpload(true)}><CloudUpload/><span><b>Yeni içerik yükle</b><small>MKV, MP4 veya MOV ekle</small></span></button><button><Image/><span><b>Görsel kitaplığı</b><small>Kapak ve arka planları yönet</small></span></button><button><Subtitles/><span><b>Parça editörü</b><small>Ses ve altyazıları düzenle</small></span></button></div></section>
</main>{upload&&<UploadModal onClose={()=>setUpload(false)}/>}</div>}
const Stat=({icon,value,label,note}:{icon:React.ReactNode;value:string;label:string;note:string})=><div className="stat"><span>{icon}</span><div><strong>{value}</strong><p>{label}</p><small>{note}</small></div></div>
const Job=({title,stage,progress,eta}:{title:string;stage:string;progress:number;eta:string})=><div className="job"><div className="job-icon"><Film/></div><div><strong>{title}</strong><span>{stage}</span><i><b style={{width:`${progress}%`}}/></i><small>{progress}% · {eta}</small></div></div>
const UploadModal=({onClose}:{onClose:()=>void})=><div className="modal"><div className="upload-card"><button className="x" onClick={onClose}>×</button><div className="upload-title"><span><CloudUpload/></span><div><h2>Yeni içerik yükle</h2><p>Kaynak dosyayı ekle; ses, altyazı ve kalite varyantları otomatik algılansın.</p></div></div><div className="drop"><CloudUpload size={38}/><strong>MKV, MP4 veya MOV dosyasını buraya bırak</strong><span>ya da bilgisayarından seç</span><button>Dosya seç</button><small>Maksimum dosya boyutu Hugging Face yapılandırmasına bağlıdır.</small></div><div className="form"><label>İçerik adı<input placeholder="Örn. Son Işık"/></label><label>İçerik türü<select><option>Kısa Film</option><option>Film</option><option>Belgesel</option></select></label></div><div className="modal-actions"><button onClick={onClose}>Vazgeç</button><button className="primary">Taslak oluştur</button></div></div></div>
createRoot(document.getElementById('root')!).render(<App/>);
